package com.dominique.utadamusic.domain;

public class ListSong {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_song.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_song.song_id
     *
     * @mbggenerated
     */
    private Integer songId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column list_song.song_list_id
     *
     * @mbggenerated
     */
    private Integer songListId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_song.id
     *
     * @return the value of list_song.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_song.id
     *
     * @param id the value for list_song.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_song.song_id
     *
     * @return the value of list_song.song_id
     *
     * @mbggenerated
     */
    public Integer getSongId() {
        return songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_song.song_id
     *
     * @param songId the value for list_song.song_id
     *
     * @mbggenerated
     */
    public void setSongId(Integer songId) {
        this.songId = songId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column list_song.song_list_id
     *
     * @return the value of list_song.song_list_id
     *
     * @mbggenerated
     */
    public Integer getSongListId() {
        return songListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column list_song.song_list_id
     *
     * @param songListId the value for list_song.song_list_id
     *
     * @mbggenerated
     */
    public void setSongListId(Integer songListId) {
        this.songListId = songListId;
    }
}